<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
        // async函数返回一个Promise对象，可以使用then方法添加回调函数。当函数执行的时候，一旦遇到await就会先返回，等到异步操作完成，再接着执行函数体内后面的语句。
        // function timeout(ms){
        //     return new Promise(resolve => {
        //         console.log(ms);
        //         setTimeout(resolve, ms);
        //     })
        // }

        // async function asyncPrint(value, ms) {
        //     await timeout(ms);
        //     console.log(value);
        // }

        // asyncPrint('hello world', 5000);
        // 先执行timeout,打印5000
        // 再执行asyncPrint里面的打印，5s后打印'hello world'

        // async function timeout(ms){
        //     await new Promise(resolve => {
        //         console.log(ms);
        //         setTimeout(resolve, ms);
        //     })
        // }

        // async function asyncPrint(value, ms) {
        //     await timeout(ms);
        //     console.log(value);
        // }

        // asyncPrint('hello world', 5000);

        // async函数返回一个Promise对象
        // async function f(){
        //     return 'hello world';
        // }

        // f().then(v => console.log(v));
        // hello world
        
        // async函数内部抛出错误，会导致返回的Promise对象变成reject状态。抛出的错误对象会被catch方法回调函数接收到
        // async function f(){
        //     throw new Error('出错了');
        // }

        // f().then(
        //     v => console.log(v),
        //     e => console.log(e)
        // );
        // Error: 出错了

        // async function getTitle(url) {
        //     let response = await fetch(url);
        //     let html = await response.text();
        //     return html.match(/<titke>([\s\S]+)<\/title>/i)[1];
        // }
        // getTitle('https://tc39.github.io/ecma262/').then(console.log)

        // async function f() {
        //     return await 123;
        // }

        // f().then(v=>console.log(v));    //123

        async function f() {
            await new Promise(function(resolve, reject){
                throw new Error('出错了');
            })
        }
        f()
            .then(v => console.log(v))
            .catch(e => console.log(e));
            // Error: 出错了
    </script>
</body>
</html>